id: P4950A4B9
initial_creation_type: ocr
source_metadata:
  volumes:
    667db4dafbb24cdb85d53b7671307269:
      base_file: v116.txt
      image_group_id: I1PD95961
      title: སྨོན་ལམ་རིན་པོ་ཆེའི་རྒྱལ་པོ།
      total_pages: 1880
      volume_number: 116
